name: Refresh Google Scholar citations
# Manual trigger only - update whenever you want, complete control over timing

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-citations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

            - name: Install dependencies
              run: bundle install --jobs 4 --retry 3

            - name: Build site (refreshes Scholar cache)
        env:
          LANG: en_US.UTF-8
          LC_ALL: en_US.UTF-8
        run: bundle exec jekyll build

      - name: Commit updated Scholar cache
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          # Add cache and data directories
          git add _cache/ _data/
          
          # Check if there are any staged changes
          if git diff --staged --quiet; then
            echo "No citation-related changes to commit."
          else
            echo "Changes detected, committing..."
            git commit -m "chore: refresh Google Scholar cache [skip ci]"
            git push
            echo "Successfully committed and pushed changes."
          fi